AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Kontaktformular API mit API Gateway, Lambda und SES.

Resources:
  ContactApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/app.handler
      Runtime: nodejs18.x
      Events:
        ContactFormApi:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /contact
            Method: post
      Environment:
        Variables:
          EMAIL_RECIPIENT: "test@example.com"
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - ses:SendEmail
            Resource: "*"

Outputs:
  ContactApiUrl:
    Description: "API Gateway Endpoint URL"
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact"
